### PR TITLE
Ide console - Initial layout

### PR DESCRIPTION
**Pull request by Supermn54**
Initial layout for IDE console web page.

### CODE REVIEW

**Review by wollmank — APPROVED** [review]
Looks good. I might be a good idea to remove the clientID and clientSecret before merging.

**Comment by Supermn54** [comment]
Updated keys.js so that my details aren't included.

**Comment by Supermn54** [comment]
Update PR with the following:
-Deleted {{>navigation}} and {{>footer}} from main.handlebars
-Deleted partials folder

**Review by wollmank — APPROVED** [review]

**Review by bonhamjp — APPROVED** [review]
Looks great!

**Pull request merged**
